export const EMERGENCYCONTACT_GET_ONE_REQUEST = 'EMERGENCYCONTACT_GET_ONE_REQUEST';
export const EMERGENCYCONTACT_GET_ONE_SUCCESS = 'EMERGENCYCONTACT_GET_ONE_SUCCESS';
export const EMERGENCYCONTACT_GET_ONE_FAIL = 'EMERGENCYCONTACT_GET_ONE_FAIL';
export const EMERGENCYCONTACT_GET_ONE_RESET = 'EMERGENCYCONTACT_GET_ONE_RESET';

export const EMERGENCYCONTACT_CREATE_REQUEST = 'EMERGENCYCONTACT_CREATE_REQUEST';
export const EMERGENCYCONTACT_CREATE_SUCCESS = 'EMERGENCYCONTACT_CREATE_SUCCESS';
export const EMERGENCYCONTACT_CREATE_FAIL = 'EMERGENCYCONTACT_CREATE_FAIL';
export const EMERGENCYCONTACT_CREATE_RESET = 'EMERGENCYCONTACT_CREATE_RESET';

export const EMERGENCYCONTACT_UPDATE_REQUEST = 'EMERGENCYCONTACT_UPDATE_REQUEST';
export const EMERGENCYCONTACT_UPDATE_SUCCESS = 'EMERGENCYCONTACT_UPDATE_SUCCESS';
export const EMERGENCYCONTACT_UPDATE_FAIL = 'EMERGENCYCONTACT_UPDATE_FAIL';
export const EMERGENCYCONTACT_UPDATE_RESET = 'EMERGENCYCONTACT_UPDATE_RESET';