export const POICATEGORY_LIST_REQUEST = 'POICATEGORY_LIST_REQUEST';
export const POICATEGORY_LIST_SUCCESS = 'POICATEGORY_LIST_SUCCESS';
export const POICATEGORY_LIST_FAIL = 'POICATEGORY_LIST_FAIL';
export const POICATEGORY_LIST_RESET = 'POICATEGORY_LIST_RESET';

export const POICATEGORY_CREATE_REQUEST = 'POICATEGORY_CREATE_REQUEST';
export const POICATEGORY_CREATE_SUCCESS = 'POICATEGORY_CREATE_SUCCESS';
export const POICATEGORY_CREATE_FAIL = 'POICATEGORY_CREATE_FAIL';
export const POICATEGORY_CREATE_RESET = 'POICATEGORY_CREATE_RESET';

export const POICATEGORY_UPDATE_INIT = 'POICATEGORY_UPDATE_INIT';

export const POICATEGORY_UPDATE_REQUEST = 'POICATEGORY_UPDATE_REQUEST';
export const POICATEGORY_UPDATE_SUCCESS = 'POICATEGORY_UPDATE_SUCCESS';
export const POICATEGORY_UPDATE_FAIL = 'POICATEGORY_UPDATE_FAIL';
export const POICATEGORY_UPDATE_RESET = 'POICATEGORY_UPDATE_RESET';

export const POICATEGORY_DELETE_REQUEST = 'POICATEGORY_DELETE_REQUEST';
export const POICATEGORY_DELETE_SUCCESS = 'POICATEGORY_DELETE_SUCCESS';
export const POICATEGORY_DELETE_FAIL = 'POICATEGORY_DELETE_FAIL';
