export const POI_LIST_REQUEST = 'POI_LIST_REQUEST';
export const POI_LIST_SUCCESS = 'POI_LIST_SUCCESS';
export const POI_LIST_FAIL = 'POI_LIST_FAIL';

export const POI_CREATE_REQUEST = 'POI_CREATE_REQUEST';
export const POI_CREATE_SUCCESS = 'POI_CREATE_SUCCESS';
export const POI_CREATE_FAIL = 'POI_CREATE_FAIL';

export const POI_UPDATE_INIT = 'POI_UPDATE_INIT';

export const POI_UPDATE_REQUEST = 'POI_UPDATE_REQUEST';
export const POI_UPDATE_SUCCESS = 'POI_UPDATE_SUCCESS';
export const POI_UPDATE_FAIL = 'POI_UPDATE_FAIL';

export const POI_DELETE_REQUEST = 'POI_DELETE_REQUEST';
export const POI_DELETE_SUCCESS = 'POI_DELETE_SUCCESS';
export const POI_DELETE_FAIL = 'POI_DELETE_FAIL';
