export const POI_ATTRIBUTE_LIST_REQUEST = 'POI_ATTRIBUTE_LIST_REQUEST';
export const POI_ATTRIBUTE_LIST_SUCCESS = 'POI_ATTRIBUTE_LIST_SUCCESS';
export const POI_ATTRIBUTE_LIST_FAIL = 'POI_ATTRIBUTE_LIST_FAIL';

export const POI_ATTRIBUTE_GET_ONE_REQUEST = 'POI_ATTRIBUTE_GET_ONE_REQUEST';
export const POI_ATTRIBUTE_GET_ONE_SUCCESS = 'POI_ATTRIBUTE_GET_ONE_SUCCESS';
export const POI_ATTRIBUTE_GET_ONE_FAIL = 'POI_ATTRIBUTE_GET_ONE_FAIL';

export const POI_ATTRIBUTE_CREATE_REQUEST = 'POI_ATTRIBUTE_CREATE_REQUEST';
export const POI_ATTRIBUTE_CREATE_SUCCESS = 'POI_ATTRIBUTE_CREATE_SUCCESS';
export const POI_ATTRIBUTE_CREATE_FAIL = 'POI_ATTRIBUTE_CREATE_FAIL';

export const POI_ATTRIBUTE_UPDATE_INIT = 'POI_ATTRIBUTE_UPDATE_INIT';

export const POI_ATTRIBUTE_UPDATE_REQUEST = 'POI_ATTRIBUTE_UPDATE_REQUEST';
export const POI_ATTRIBUTE_UPDATE_SUCCESS = 'POI_ATTRIBUTE_UPDATE_SUCCESS';
export const POI_ATTRIBUTE_UPDATE_FAIL = 'POI_ATTRIBUTE_UPDATE_FAIL';

export const POI_ATTRIBUTE_DELETE_REQUEST = 'POI_ATTRIBUTE_DELETE_REQUEST';
export const POI_ATTRIBUTE_DELETE_SUCCESS = 'POI_ATTRIBUTE_DELETE_SUCCESS';
export const POI_ATTRIBUTE_DELETE_FAIL = 'POI_ATTRIBUTE_DELETE_FAIL';
