export const GUIDE_LIST_REQUEST = 'GUIDE_LIST_REQUEST';
export const GUIDE_LIST_SUCCESS = 'GUIDE_LIST_SUCCESS';
export const GUIDE_LIST_FAIL = 'GUIDE_LIST_FAIL';

export const GUIDE_CREATE_REQUEST = 'GUIDE_CREATE_REQUEST';
export const GUIDE_CREATE_SUCCESS = 'GUIDE_CREATE_SUCCESS';
export const GUIDE_CREATE_FAIL = 'GUIDE_CREATE_FAIL';

export const GUIDE_UPDATE_INIT = 'GUIDE_UPDATE_INIT';
export const GUIDE_UPDATE_REQUEST = 'GUIDE_UPDATE_REQUEST';
export const GUIDE_UPDATE_SUCCESS = 'GUIDE_UPDATE_SUCCESS';
export const GUIDE_UPDATE_FAIL = 'GUIDE_UPDATE_FAIL';