export const PHOTOS_LIST_REQUEST = 'PHOTOS_LIST_REQUEST';
export const PHOTOS_LIST_SUCCESS = 'PHOTOS_LIST_SUCCESS';
export const PHOTOS_LIST_FAIL = 'PHOTOS_LIST_FAIL';
export const PHOTOS_LIST_RESET = 'PHOTOS_LIST_RESET';

export const PHOTOS_UPDATE_REQUEST = 'PHOTOS_UPDATE_REQUEST';
export const PHOTOS_UPDATE_SUCCESS = 'PHOTOS_UPDATE_SUCCESS';
export const PHOTOS_UPDATE_FAIL = 'PHOTOS_UPDATE_FAIL';
export const PHOTOS_UPDATE_RESET = 'PHOTOS_UPDATE_RESET';