export const VIDEO_CATEGORY_LIST_REQUEST = 'VIDEO_CATEGORY_LIST_REQUEST';
export const VIDEO_CATEGORY_LIST_SUCCESS = 'VIDEO_CATEGORY_LIST_SUCCESS';
export const VIDEO_CATEGORY_LIST_FAIL = 'VIDEO_CATEGORY_LIST_FAIL';

export const VIDEO_CATEGORY_CREATE_REQUEST = 'VIDEO_CATEGORY_CREATE_REQUEST';
export const VIDEO_CATEGORY_CREATE_SUCCESS = 'VIDEO_CATEGORY_CREATE_SUCCESS';
export const VIDEO_CATEGORY_CREATE_FAIL = 'VIDEO_CATEGORY_CREATE_FAIL';

export const VIDEO_CATEGORY_UPDATE_INIT = 'VIDEO_CATEGORY_UPDATE_INIT';
export const VIDEO_CATEGORY_UPDATE_REQUEST = 'VIDEO_CATEGORY_UPDATE_REQUEST';
export const VIDEO_CATEGORY_UPDATE_SUCCESS = 'VIDEO_CATEGORY_UPDATE_SUCCESS';
export const VIDEO_CATEGORY_UPDATE_FAIL = 'VIDEO_CATEGORY_UPDATE_FAIL';