export const PAYING_GUEST_LIST_REQUEST = 'PAYING_GUEST_LIST_REQUEST';
export const PAYING_GUEST_LIST_SUCCESS = 'PAYING_GUEST_LIST_SUCCESS';
export const PAYING_GUEST_LIST_FAIL = 'PAYING_GUEST_LIST_FAIL';

export const PAYING_GUEST_CREATE_REQUEST = 'PAYING_GUEST_CREATE_REQUEST';
export const PAYING_GUEST_CREATE_SUCCESS = 'PAYING_GUEST_CREATE_SUCCESS';
export const PAYING_GUEST_CREATE_FAIL = 'PAYING_GUEST_CREATE_FAIL';

export const PAYING_GUEST_UPDATE_INIT = 'PAYING_GUEST_UPDATE_INIT';
export const PAYING_GUEST_UPDATE_REQUEST = 'PAYING_GUEST_UPDATE_REQUEST';
export const PAYING_GUEST_UPDATE_SUCCESS = 'PAYING_GUEST_UPDATE_SUCCESS';
export const PAYING_GUEST_UPDATE_FAIL = 'PAYING_GUEST_UPDATE_FAIL';