export const DEPT_OFF_JURISDICTION_LIST_REQUEST = 'DEPT_OFF_JURISDICTION_LIST_REQUEST';
export const DEPT_OFF_JURISDICTION_LIST_SUCCESS = 'DEPT_OFF_JURISDICTION_LIST_SUCCESS';
export const DEPT_OFF_JURISDICTION_LIST_FAIL = 'DEPT_OFF_JURISDICTION_LIST_FAIL';

export const DEPT_OFF_JURISDICTION_CREATE_REQUEST = 'DEPT_OFF_JURISDICTION_CREATE_REQUEST';
export const DEPT_OFF_JURISDICTION_CREATE_SUCCESS = 'DEPT_OFF_JURISDICTION_CREATE_SUCCESS';
export const DEPT_OFF_JURISDICTION_CREATE_FAIL = 'DEPT_OFF_JURISDICTION_CREATE_FAIL';

export const DEPT_OFF_JURISDICTION_UPDATE_INIT = 'DEPT_OFF_JURISDICTION_UPDATE_INIT';
export const DEPT_OFF_JURISDICTION_UPDATE_REQUEST = 'DEPT_OFF_JURISDICTION_UPDATE_REQUEST';
export const DEPT_OFF_JURISDICTION_UPDATE_SUCCESS = 'DEPT_OFF_JURISDICTION_UPDATE_SUCCESS';
export const DEPT_OFF_JURISDICTION_UPDATE_FAIL = 'DEPT_OFF_JURISDICTION_UPDATE_FAIL';