export const TOURIST_CIRCUIT_LIST_REQUEST = 'TOURIST_CIRCUIT_LIST_REQUEST';
export const TOURIST_CIRCUIT_LIST_SUCCESS = 'TOURIST_CIRCUIT_LIST_SUCCESS';
export const TOURIST_CIRCUIT_LIST_FAIL = 'TOURIST_CIRCUIT_LIST_FAIL';

export const TOURIST_CIRCUIT_CREATE_REQUEST = 'TOURIST_CIRCUIT_CREATE_REQUEST';
export const TOURIST_CIRCUIT_CREATE_SUCCESS = 'TOURIST_CIRCUIT_CREATE_SUCCESS';
export const TOURIST_CIRCUIT_CREATE_FAIL = 'TOURIST_CIRCUIT_CREATE_FAIL';

export const TOURIST_CIRCUIT_UPDATE_INIT = 'TOURIST_CIRCUIT_UPDATE_INIT';
export const TOURIST_CIRCUIT_UPDATE_REQUEST = 'TOURIST_CIRCUIT_UPDATE_REQUEST';
export const TOURIST_CIRCUIT_UPDATE_SUCCESS = 'TOURIST_CIRCUIT_UPDATE_SUCCESS';
export const TOURIST_CIRCUIT_UPDATE_FAIL = 'TOURIST_CIRCUIT_UPDATE_FAIL';