export const CITY_LIST_REQUEST = 'CITY_LIST_REQUEST';
export const CITY_LIST_SUCCESS = 'CITY_LIST_SUCCESS';
export const CITY_LIST_FAIL = 'CITY_LIST_FAIL';
export const CITY_LIST_RESET = 'CITY_LIST_RESET';

export const CITY_CREATE_REQUEST = 'CITY_CREATE_REQUEST';
export const CITY_CREATE_SUCCESS = 'CITY_CREATE_SUCCESS';
export const CITY_CREATE_FAIL = 'CITY_CREATE_FAIL';
export const CITY_CREATE_RESET = 'CITY_CREATE_RESET';

export const CITY_UPDATE_REQUEST = 'CITY_UPDATE_REQUEST';
export const CITY_UPDATE_SUCCESS = 'CITY_UPDATE_SUCCESS';
export const CITY_UPDATE_FAIL = 'CITY_UPDATE_FAIL';
export const CITY_UPDATE_RESET = 'CITY_UPDATE_RESET';