export const TRAVEL_DESK_LIST_REQUEST = 'TRAVEL_DESK_LIST_REQUEST';
export const TRAVEL_DESK_LIST_SUCCESS = 'TRAVEL_DESK_LIST_SUCCESS';
export const TRAVEL_DESK_LIST_FAIL = 'TRAVEL_DESK_LIST_FAIL';

export const TRAVEL_DESK_CREATE_REQUEST = 'TRAVEL_DESK_CREATE_REQUEST';
export const TRAVEL_DESK_CREATE_SUCCESS = 'TRAVEL_DESK_CREATE_SUCCESS';
export const TRAVEL_DESK_CREATE_FAIL = 'TRAVEL_DESK_CREATE_FAIL';

export const TRAVEL_DESK_UPDATE_INIT = 'TRAVEL_DESK_UPDATE_INIT';
export const TRAVEL_DESK_UPDATE_REQUEST = 'TRAVEL_DESK_UPDATE_REQUEST';
export const TRAVEL_DESK_UPDATE_SUCCESS = 'TRAVEL_DESK_UPDATE_SUCCESS';
export const TRAVEL_DESK_UPDATE_FAIL = 'TRAVEL_DESK_UPDATE_FAIL';